
public class ChampionList {
	//Array of all LoL champions and their IDs in the following format: 
	//ID - name, description
	public static String[] championList = {
		"1 - Annie, the Dark Child",
		"2 - Olaf, the Berserker",
		"3 - Galio, the Sentinel's Sorrow",
		"4 - Twisted Fate, the Card Master",
		"5 - Xin Zhao, the Seneschal of Demacia",
		"6 - Urgot, the Headsman's Pride",
		"7 - LeBlanc, the Deceiver",
		"8 - Vladimir, the Crimson Reaper",
		"9 - Fiddlesticks, the Harbinger of Doom",
		"10 - Kayle, The Judicator",
		"11 - Master Yi, the Wuju Bladesman",
		"12 - Alistar, the Minotaur",
		"13 - Ryze, the Rogue Mage",
		"14 - Sion, The Undead Juggernaut",
		"15 - Sivir, the Battle Mistress",
		"16 - Soraka, the Starchild",
		"17 - Teemo, the Swift Scout",
		"18 - Tristana, the Megling Gunner",
		"19 - Warwick, the Blood Hunter",
		"20 - Nunu, the Yeti Rider",
		"21 - Miss Fortune, the Bounty Hunter",
		"22 - Ashe, the Frost Archer",
		"23 - Tryndamere, the Barbarian King",
		"24 - Jax, Grandmaster at Arms",
		"25 - Morgana, Fallen Angel",
		"26 - Zilean, the Chronokeeper",
		"27 - Singed, the Mad Chemist",
		"28 - Evelynn, the Widowmaker",
		"29 - Twitch, the Plague Rat",
		"30 - Karthus, the Deathsinger",
		"31 - Cho'Gath, the Terror of the Void",
		"32 - Amumu, the Sad Mummy",
		"33 - Rammus, the Armordillo",
		"34 - Anivia, the Cryophoenix",
		"35 - Shaco, the Demon Jester",
		"36 - Dr. Mundo, the Madman of Zaun",
		"37 - Sona, Maven of the Strings",
		"38 - Kassadin, the Void Walker",
		"39 - Irelia, the Will of the Blades",
		"40 - Janna, the Storm's Fury",
		"41 - Gangplank, the Saltwater Scourge",
		"42 - Corki, the Daring Bombardier",
		"43 - Karma, the Enlightened One",
		"44 - Taric, the Gem Knight",
		"45 - Veigar, the Tiny Master of Evil",
		"48 - Trundle, the Troll King",
		"50 - Swain, the Master Tactician",
		"51 - Caitlyn, the Sheriff of Piltover",
		"53 - Blitzcrank, the Great Steam Golem",
		"54 - Malphite, Shard of the Monolith",
		"55 - Katarina, the Sinister Blade",
		"56 - Nocturne, the Eternal Nightmare",
		"57 - Maokai, the Twisted Treant",
		"58 - Renekton, the Butcher of the Sands",
		"59 - Jarvan IV, the Exemplar of Demacia",
		"60 - Elise, The Spider Queen",
		"61 - Orianna, the Lady of Clockwork",
		"62 - Wukong, the Monkey King",
		"63 - Brand, the Burning Vengeance",
		"64 - Lee Sin, the Blind Monk",
		"67 - Vayne, the Night Hunter",
		"68 - Rumble, the Mechanized Menace",
		"69 - Cassiopeia, the Serpent's Embrace",
		"72 - Skarner, the Crystal Vanguard",
		"74 - Heimerdinger, the Revered Inventor",
		"75 - Nasus, the Curator of the Sands",
		"76 - Nidalee, the Bestial Huntress",
		"77 - Udyr, the Spirit Walker",
		"78 - Poppy, the Iron Ambassador",
		"79 - Gragas, the Rabble Rouser",
		"80 - Pantheon, the Artisan of War",
		"81 - Ezreal, the Prodigal Explorer",
		"82 - Mordekaiser, the Master of Metal",
		"83 - Yorick, the Gravedigger",
		"84 - Akali, the Fist of Shadow",
		"85 - Kennen, the Heart of the Tempest",
		"86 - Garen, The Might of Demacia",
		"89 - Leona, the Radiant Dawn",
		"90 - Malzahar, the Prophet of the Void",
		"91 - Talon, the Blade's Shadow",
		"92 - Riven, the Exile",
		"96 - Kog'Maw, the Mouth of the Abyss",
		"98 - Shen, Eye of Twilight",
		"99 - Lux, the Lady of Luminosity",
		"101 - Xerath, the Magus Ascendant",
		"102 - Shyvana, the Half-Dragon",
		"103 - Ahri, the Nine-Tailed Fox",
		"104 - Graves, the Outlaw",
		"105 - Fizz, the Tidal Trickster",
		"106 - Volibear, the Thunder's Roar",
		"107 - Rengar, the Pridestalker",
		"110 - Varus, the Arrow of Retribution",
		"111 - Nautilus, the Titan of the Depths",
		"112 - Viktor, the Machine Herald",
		"113 - Sejuani, the Winter's Wrath",
		"114 - Fiora, the Grand Duelist",
		"115 - Ziggs, the Hexplosives Expert",
		"117 - Lulu, the Fae Sorceress",
		"119 - Draven, the Glorious Executioner",
		"120 - Hecarim, the Shadow of War",
		"121 - Kha'Zix, the Voidreaver",
		"122 - Darius, the Hand of Noxus",
		"126 - Jayce, the Defender of Tomorrow",
		"127 - Lissandra, the Ice Witch",
		"131 - Diana, Scorn of the Moon",
		"133 - Quinn, Demacia's Wings",
		"134 - Syndra, the Dark Sovereign",
		"143 - Zyra, Rise of the Thorns",
		"150 - Gnar, the Missing Link",
		"154 - Zac, the Secret Weapon",
		"157 - Yasuo, the Unforgiven",
		"161 - Vel'Koz, the Eye of the Void",
		"201 - Braum, the Heart of the Freljord",
		"222 - Jinx, the Loose Cannon",
		"236 - Lucian, the Purifier",
		"238 - Zed, the Master of Shadows",
		"254 - Vi, the Piltover Enforcer",
		"266 - Aatrox, the Darkin Blade",
		"267 - Nami, the Tidecaller",
		"268 - Azir, the Emperor of the Sands",
		"412 - Thresh, the Chain Warden",
		"421 - Rek'Sai, the Void Burrower",
		"429 - Kalista, the Spear of Vengeance",
	};
	

	
}
